### ISSUE TITLE
Make agent pick specific gcc version

### ISSUE THREAD

**Issue by immohitrathi** [appoptics/appoptics-apm-node#129]
Hello,
I have a situation where our production servers don’t have the required gcc version i.e 4.7 and above. Now, since it’s a system library we don’t know what applications, libraries will be impacted if we upgrade gcc version. 

Please let us know if there is a possibility of installing gcc@4.7 and passing this gcc path to appoptics module using some env var or configuration 

We have tested this agent on our staging server by upgrading gcc but we want to mitigate risk in production.

**Comment by bmacnaughton** [comment]
there is not a way to do what you're asking at this time. distributing pre-built binaries is on our roadmap, but not scheduled at this point. in general, the compiler and libraries are backwards compatible. but forward compatibility is not and is typically determined by the GLIBCXX library version required by the compiler's output.

i can't guarantee it but i think there is little risk to upgrading the g++ compiler.

https://stackoverflow.com/questions/56781513/understanding-the-gcc-version-and-the-glibc-glibcxx-versions-in-more-detail

**Comment by bmacnaughton** [comment]
i'm going to close with and link this issue to our jira pre-built binaries issue. we'll notify you when the project is started and when it's done.
