### ISSUE TITLE
AppopticsAPM disabled due to: require failed: MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by lc3t35** [appoptics/appoptics-apm-node#135]
Here is the error message : 

```
  appoptics:error Can't load bindings +0ms
  appoptics:error AppopticsAPM disabled due to: require failed: MODULE_NOT_FOUND +2ms
  appoptics:error api key _stats conflicts, ignoring +0ms
```

The key is valid (if I remove the APPOPTICS_SERVICE_KEY, I have a no valid service key), this happens with the key.

First line of App.js is `require('appoptics-apm');`
Is it possible to use import syntax instead of require ?

**Comment by bmacnaughton** [comment]
is there any chance you're running on either windows or mac? the agent does not run in either environment.

we do not yet support using `import`.

**Comment by lc3t35** [comment]
yes, my test environment was on mac -> i'll test on staging which is linux based

**Comment by bmacnaughton** [comment]
we probably should detect that in the agent and issue a better message. thanks for the followup.

**Comment by lc3t35** [comment]
or simply write it in the documentation ;)

**Comment by bmacnaughton** [comment]
it is on the appoptics website, and the readme, near the top, mentions that linux is required. maybe it could add that windows and mac are not supported too.
