### ISSUE TITLE
support hapi 17.5

### ISSUE THREAD

**Issue by twiggy** [appoptics/appoptics-apm-node#16]
We are moving to appoptics if you haven't guessed. We use hapi 17.5, but i think your support ends at 16.5. I think i got it going fixing the other issue, but i wonder if i'm going to get a good transaction name since we use also use hapi-openapi to server up a swagger/open api endpoint...so just get a single api transaction name :(. So hapi 17.5 might be working fine, and it could just be the way hapi-openapi registers routes.

**Comment by bmacnaughton** [comment]
It's not clear what the issue you have is now. When you say "fixed the other issue" you mean the "log.patching()" error? That would allow the patching to continue but would not likely work as expected, though it likely would for a subset of the API.

I'm not sure what the issue with the transaction name is. Can you clarify that?

**Comment by twiggy** [comment]
Thanks, log.patching is now fixed, so hapi is loading up. but all my transactions come out named /api/v1 instead of /api/v1/users, /api/v1/comments ...we use a swagger plugin that registers routes on startup. Its possible that hapi 17.5 is basically working and i'll need to do some custom transaction naming code in a hapi event like 'preAuth'.

**Comment by twiggy** [comment]
thanks again. i think hapi 17.5 is "supported" in that it works and i can get custom tx names set albeit a little hacky.

I hacked a custom tx name by doing this. I saw setCustomTXName is only supported by express at the moment.

try {
            	h.request.raw.res._ao_metrics.txname = h.request.route.path;
            } catch(ex){console.log(ex)};

where h = the hapi object. i noticed you had commented out a _ao_metrics.txname "setter", but i'm fine using this at our own risk until a more supported option is available.

**Comment by bmacnaughton** [comment]
nice hack - that's pretty much the same approach i'll take with some additional checks most likely.

says, if you can drop me your email (package has one for me) i'll update you when i have we have native custom txname support.

it's kind of amazing that hapi 17.5 is working. it does not pass our tests; i might need to change them some based on your input.

thanks for you efforts.

**Comment by bmacnaughton** [comment]
v5.7.0 supports hapi in my tests. See https://github.com/appoptics/appoptics-apm-node/releases/tag/v5.7.0.

While it is different than your implementation the custom name function should not break your code. The custom name function takes a single parameter - the hapi request object (`request` in `handler(request, h)`).

I'm not sure why you're using `h` as opposed to `request`, so I could be missing something. If so let me know and I'll change it for the next release.

The default TransactionName has changed as well - it will be `hapi.<function-name>.<request.route.method><request.route.path>` where function-name is the name of the handler function for that route or `(anonymous)` if no name.

Let me know if you run into any problems or have any questions. Thank you for your issues.
