### ISSUE TITLE
http.js probe corrupting streamed data

### ISSUE THREAD

**Issue by twiggy** [appoptics/appoptics-apm-node#22]
Having a weird issue where when we upload an image the data is corrupted before we send it off to s3.

I imagine you could reproduce by having curl POST an image body to a node/hapi endpoint, write a file out, and see if its corrupted in some way. If I have time later maybe i can create a simple test case.

Did a bunch of digging and I can remove the behavior by disabling the 'emit' shimmer wrap.

In http.js 

 `shimmer.wrap(proto, 'emit', function (realEmit) {`

If just have the 

```
if (type !== 'request') {
        return realEmit.apply(this, arguments);
      }
```

always be true everything is also fine.

I did a lot of trial and error stuff and I think it has something to with the patchEmitter(req)  and ao.requestStore.run() stuff. I'm not really sure what .run() does so I'm kind of at a loss from there.

The corruption is weird, the file length seems to be be the same, but the data isn't the same. I might see if I can do a binary diff later as well. Maybe encoding is being changed in some way.

**Comment by bmacnaughton** [comment]
Thanks for the investigation and trial and error work. `ao.requestStore.run()` causes the emitter to run with the correct continuation-local-storage context. cls is used to thread the events of a single transaction together. it's very odd that corruption occurs because that's the only (intended consequence). `ao.requestStore.run()` directly calls the cls-hooked `namespace.run()` function. If you can provide a test case that would be fantastic.

**Comment by twiggy** [comment]
I think I finally figured out what is happening.

We have this block of code.

```
	let leadingChunk = stream.read(4100);
	let {ext, mime} = fileType(leadingChunk);
	stream.unshift(leadingChunk);
```

stream.unshift is an official Node js function on streams.

The appoptics code is using this github project called event-unshift. I noticed in the debugger that our stream object is basically getting the stream's unshift function replaced.

I'm not 100% sure but i think they are 2 entirely different purposes.

Anyways I think our unshift basically never occurs and so who knows what is happening to the socket. 

I have a smallish testing code now if you still want it. Not super simple though. I think node 8.x might have sort of changed the way these things behave.

Silver lining we found a race condition where stream.read has to wait till stream.complete == true at least

**Comment by bmacnaughton** [comment]
Thank you! event-unshift is used to add event-listeners before existing event-listeners. The choice of names is clearly an issue - I'll change the function name so it doesn't conflict. (It's been there since 0.9.17.) Will note here when it's fixed.

**Comment by bmacnaughton** [comment]
It's been fixed a while but I haven't released it. Trying to get a number of changes in for a bigger release. Let me know if it's important and I can go back and release this fix independently.

**Comment by twiggy** [comment]
we got our trial extended till end of September so i think I'm fine waiting for a bigger release. if you think it'll be out in the next week or two should be fine.

**Comment by cheempz** [comment]
@twiggy thanks for your patience on this one, we just released version 5.6.0 that should fix this issue, please give it a try.

**Comment by cheempz** [comment]
Closing, please feel free to create another issue if the new version didn't address this.

**Comment by twiggy** [comment]
sorry i didn't get a chance to try the RC version. Hopefully tonight or tomorrow i can up the version and run some tests locally. Thanks!

**Comment by cheempz** [comment]
No worries, please note that the fix is now released and available in GA versions 5.6.0+.

**Comment by twiggy** [comment]
seems fixed in my testing

**Comment by bmacnaughton** [comment]
Thank you for testing and confirming the fix.
