### ISSUE TITLE
Postgres connection issues with newer drivers

### ISSUE THREAD

**Issue by chooban** [appoptics/appoptics-apm-node#28]
I'm currently trying to evaluate App Optics in combination with node and postgres. I have a version of the server app running on node 10.2.1 inside a docker container, but when I try to start the server I get an error:

```
2018-09-20T11:03:00.957Z appoptics:warn ao.bind  - no context Error: CLS NOT ACTIVE
  at Object.exports.bind (./node_modules/appoptics-apm/dist/index.js:659:17)
  at Client.connect (./node_modules/appoptics-apm/dist/probes/pg.js:78:49)
  at Pool.connect (/./node_modules/pg-pool/index.js:207:12)
  at config.promise (./node_modules/pg-promise/lib/connect.js:22:11)
  at new Promise (<anonymous>)
  at Object.promise (./node_modules/pg-promise/lib/promise.js:23:20)
  at poolConnect (./node_modules/pg-promise/lib/connect.js:11:19)
  at Object.pool (./node_modules/pg-promise/lib/connect.js:127:24)
  at Database.query (./node_modules/pg-promise/lib/database.js:304:36)
  at Database.query (./node_modules/massive/lib/database.js:377:29)
  at Database.reload (./node_modules/massive/lib/database.js:202:10)
  at module.exports (./node_modules/massive/index.js:32:59)
  at module.exports (./packages/.../server/config/database.js:6:10)
  at listen (./packages/.../server/server.js:21:28)
  at Object.<anonymous> (./packages/.../server/server.js:17:1)
  at Module._compile (internal/modules/cjs/loader.js:702:30)
```

After this, I get information about the http requests on my dashboard, but the database connection isn't working. Any request that hits the database gets a similar warning.

The chain of dependencies means that we're using the 7.x series of pg drivers, so is there a roadmap for when you might be upgrading to use those, or am I barking up the wrong tree with that?

**Comment by bmacnaughton** [comment]
It's on our list to fix but I don't have a specific time-frame for you. There are currently 4 packages that require non-trivial fixes due to significant changes in their implementation.

https://node-postgres.com/guides/upgrading

**Comment by chooban** [comment]
If I can get a dev environment up and running I can take a look at the work required to update it if that would be useful? I tried running tests on the mac and mysql blew up, but I've added a skip option to it. Little steps, eh?

**Comment by paps** [comment]
Also facing this issue (log message `appoptics:warn ao.bind  - no context Error: CLS NOT ACTIVE`).

I'm using `any-db`, `any-db-postgres` and `any-db-transaction` with `appoptics-apm` 5.6.1

**Comment by bmacnaughton** [comment]
@paps - are you also running pg 7.x drivers? if not, please provide the stack trace with the lost context. i've recently fixed quite a few of those (going to be in the 5.9.0 release) but I haven't seen them with `pg` for our currently supported versions.

**Comment by bmacnaughton** [comment]
@chooban - be happy to collaborate with you on this. our c-library doesn't compile/execute on a mac so you'll need a linux docker container to get things working. i can spend some time with you on getting a dev environment set up (given the caveat that i run linux, not mac) if you are interested in pursuing this.

i will be taking a look at it pretty soon.

**Comment by bmacnaughton** [comment]
@paps - no, i think you're ok running pg@6.1.5. That version passes our tests, but with any system like postgres there are many situations we don't test. Can you provide the stack trace associated with those errors? And, if you know the query that is being used it would be great to get that as well.

useful info:
- os
- node version
- npm ls --json
- stack trace from error
- query if you know what is being executed.

thank you so much for your help!

**Comment by chooban** [comment]
@bmacnaughton Apologies for the delay. I saw the notification then it got swamped by others. Happy to take a look at this with you. Do you have a dockerfile for getting up and running with it?

**Comment by bmacnaughton** [comment]
no worries. i get swamped with notifications too.

appoptics-apm v5.9.3 is just published. it has a number of changes primarily in v7 support. If you can give that a try I'd appreciate it. the biggest change in v7 is the way in which the pool works. v6 is somewhat challenging as it tries to maintain compatibility with previous versions and also implement the v7 changes.

We do have a docker-compose file and collection of docker files that can be used to develop and provide the testing database. it's not hard but there are a fair number of moving pieces. i'd be happy to work with you on that if 5.9.3 doesn't fix your issues and you can't use pg@7.

the CONTRIBUTING.md file has some hints about testing but it's not perfect. I develop using Linux so the making things work on the mac is not so well defined. Also, reading `env.sh` is helpful for two things:

1. it sets up APPOPTICS_SERVICE_KEY in a way that requires AO_TOKEN_STG be defined (I use our staging server for testing when I do test against a live backend) though the unit and probe tests do not require using a live collector.
2) i generally give it the "bash" argument and it sets up things for my command line environment. that's what you'd use inside the "main" container.

Also note that in the docker-compose file setting up the main container is commented out (I don't use it) and that it's an old version of node specified in `test/docker/main.yml` - the line to install node should change from v4 to whatever version you want to run.

**Comment by bmacnaughton** [comment]
One additional question - are you using callbacks, promises, or events to handle the asynchronous calls?

**Comment by bmacnaughton** [comment]
We released new postgres probes in v5.9.3. Could you give those a try and let us know whether it addresses your issues? They specifically addressed the pg v7 promises and pooled connections. our v6 instrumentation does not support promises but continues to support events and callbacks.

**Comment by bmacnaughton** [comment]
@chooban - the latest commit includes a a docker setup for the mac. It's `test/docker/mac-os-test-env` and can be used for developing and/or testing.

**Comment by chooban** [comment]
Thanks, taking a look at it now as we're using a newer version of koa-router which also causes issues!

With the latest APM package, I get an error trying to construct a Router: `TypeError: Router is not a constructor`. If I do the simplest thing of printing out the function as a string, I get `app => patchApp(app, router)`. Printing it out when I've not included the APM package gives me a recognisable constructor function.

**Comment by chooban** [comment]
As the original reporter I'm happy that the issue is resolved. :+1:

**Comment by bmacnaughton** [comment]
I believe this is addressed with the latest versions. And the koa-router problem has been addressed with your help - thank you.
