### ISSUE TITLE
patchPathMethods removes `fs.realpath.native` and `fs.realpathSync.native` methods.

### ISSUE THREAD

**Issue by jdalton** [appoptics/appoptics-apm-node#34]
[`patchPathMethods()`](https://github.com/appoptics/appoptics-apm-node/blob/ce38048105bd526803587df891ad6c7e422d4bc0/lib/probes/fs.js#L90-L113) removes [`fs.realpath.native`](https://nodejs.org/api/fs.html#fs_fs_realpath_native_path_options_callback) and [`fs.realpathSync.native`](https://nodejs.org/api/fs.html#fs_fs_realpathsync_native_path_options) methods.

**Comment by bmacnaughton** [comment]
I can fix this in our code if, as I suspect it might be, tricky for you to get around.  By fix I mean that I can make the `realpath.native` and `realpathSync.native` methods available on the patched function.

**Comment by jdalton** [comment]
Thank you, that would be great! They are publicly accessible and documented Node methods, which means appoptics-apm is potentially breaking other folks code that use them too.

**Comment by bmacnaughton** [comment]
they'll be in the next release of appoptics-apm.

**Comment by bmacnaughton** [comment]
Release in v5.9.0
