### ISSUE TITLE
Ignore the transaction by url/path

### ISSUE THREAD

**Issue by Igor-Techsee** [appoptics/appoptics-apm-node#40]
We are using socket.io and need to ignore socket.io requests to get real response time average. Is there any solution for this?

**Comment by bmacnaughton** [comment]
Sorry for the delay - I'd been traveling for Thanksgiving.

I'll take a look at it this week.

**Comment by bmacnaughton** [comment]
We do not currently support this. If you have specific use cases or ideas we would appreciate your input.  I'm closing this but please comment so we can take your needs into account as we work on this feature.

**Comment by Igor-Techsee** [comment]
The use case is to ignore some requests/transactions by path ( '/socket.io' in our case)

**Comment by bmacnaughton** [comment]
I am working on this. It will be part of the next major release (6.0.0) that will implement a `specialUrl` configuration to ignore requests/transactions.

It will also change the low-level API, use N-API instead of Nan for appoptics-bindings, and make significant internal changes.
